/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:04:57 GMT 2016
 */

package com.rickhanberryfinal.evosuite.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.DrinkRecipe;
import com.rickhanberryfinal.services.impl.DrinkRecipeServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DrinkRecipeServiceImpl_ESTest extends DrinkRecipeServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DrinkRecipeServiceImpl drinkRecipeServiceImpl0 = new DrinkRecipeServiceImpl();
      // Undeclared exception!
      try { 
        drinkRecipeServiceImpl0.findAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.DrinkRecipeServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DrinkRecipeServiceImpl drinkRecipeServiceImpl0 = new DrinkRecipeServiceImpl();
      // Undeclared exception!
      try { 
        drinkRecipeServiceImpl0.save((DrinkRecipe) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.DrinkRecipeServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DrinkRecipeServiceImpl drinkRecipeServiceImpl0 = new DrinkRecipeServiceImpl();
      // Undeclared exception!
      try { 
        drinkRecipeServiceImpl0.delete((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.DrinkRecipeServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DrinkRecipeServiceImpl drinkRecipeServiceImpl0 = new DrinkRecipeServiceImpl();
      // Undeclared exception!
      try { 
        drinkRecipeServiceImpl0.findOne((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.DrinkRecipeServiceImpl", e);
      }
  }
}
