/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:08:49 GMT 2016
 */

package com.rickhanberryfinal.evosuite.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.UnitOfMeasure;
import com.rickhanberryfinal.services.impl.UnitOfMeasureServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UnitOfMeasureServiceImpl_ESTest extends UnitOfMeasureServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnitOfMeasureServiceImpl unitOfMeasureServiceImpl0 = new UnitOfMeasureServiceImpl();
      // Undeclared exception!
      try { 
        unitOfMeasureServiceImpl0.findAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.UnitOfMeasureServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnitOfMeasureServiceImpl unitOfMeasureServiceImpl0 = new UnitOfMeasureServiceImpl();
      // Undeclared exception!
      try { 
        unitOfMeasureServiceImpl0.save((UnitOfMeasure) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.UnitOfMeasureServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnitOfMeasureServiceImpl unitOfMeasureServiceImpl0 = new UnitOfMeasureServiceImpl();
      // Undeclared exception!
      try { 
        unitOfMeasureServiceImpl0.delete((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.UnitOfMeasureServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UnitOfMeasureServiceImpl unitOfMeasureServiceImpl0 = new UnitOfMeasureServiceImpl();
      // Undeclared exception!
      try { 
        unitOfMeasureServiceImpl0.findOne((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.UnitOfMeasureServiceImpl", e);
      }
  }
}
