/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:07:34 GMT 2016
 */

package com.rickhanberryfinal.evosuite.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.Vendor;
import com.rickhanberryfinal.services.impl.VendorServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VendorServiceImpl_ESTest extends VendorServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VendorServiceImpl vendorServiceImpl0 = new VendorServiceImpl();
      // Undeclared exception!
      try { 
        vendorServiceImpl0.save((Vendor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.VendorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VendorServiceImpl vendorServiceImpl0 = new VendorServiceImpl();
      // Undeclared exception!
      try { 
        vendorServiceImpl0.findAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.VendorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VendorServiceImpl vendorServiceImpl0 = new VendorServiceImpl();
      Long long0 = new Long((-67L));
      // Undeclared exception!
      try { 
        vendorServiceImpl0.delete(long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.VendorServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VendorServiceImpl vendorServiceImpl0 = new VendorServiceImpl();
      Long long0 = new Long((-25L));
      // Undeclared exception!
      try { 
        vendorServiceImpl0.findOne(long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.services.impl.VendorServiceImpl", e);
      }
  }
}
