/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:04:08 GMT 2016
 */

package com.rickhanberryfinal.evosuite.webservices;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.Allergens;
import com.rickhanberryfinal.webservices.AllergensWebService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.http.ResponseEntity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AllergensWebService_ESTest extends AllergensWebService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Allergens allergens0 = new Allergens();
      AllergensWebService allergensWebService0 = new AllergensWebService();
      // Undeclared exception!
      try { 
        allergensWebService0.updateAllergens(allergens0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Allergens allergens0 = new Allergens();
      Long long0 = new Long((-59L));
      allergens0.setId(long0);
      AllergensWebService allergensWebService0 = new AllergensWebService();
      // Undeclared exception!
      try { 
        allergensWebService0.updateAllergens(allergens0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Allergens allergens0 = new Allergens();
      Long long0 = new Long((-59L));
      allergens0.setId(long0);
      AllergensWebService allergensWebService0 = new AllergensWebService();
      ResponseEntity<Allergens> responseEntity0 = allergensWebService0.createAllergens(allergens0);
      assertFalse(responseEntity0.hasBody());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AllergensWebService allergensWebService0 = new AllergensWebService();
      Allergens allergens0 = new Allergens();
      // Undeclared exception!
      try { 
        allergensWebService0.createAllergens(allergens0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AllergensWebService allergensWebService0 = new AllergensWebService();
      // Undeclared exception!
      try { 
        allergensWebService0.getAllergens((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AllergensWebService allergensWebService0 = new AllergensWebService();
      // Undeclared exception!
      try { 
        allergensWebService0.getAllAllergenss();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AllergensWebService allergensWebService0 = new AllergensWebService();
      // Undeclared exception!
      try { 
        allergensWebService0.deleteAllergens((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.AllergensWebService", e);
      }
  }
}
