/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:06:16 GMT 2016
 */

package com.rickhanberryfinal.evosuite.webservices;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.DrinkRecipe;
import com.rickhanberryfinal.webservices.DrinkRecipeWebService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.http.ResponseEntity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DrinkRecipeWebService_ESTest extends DrinkRecipeWebService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      DrinkRecipe drinkRecipe0 = new DrinkRecipe();
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.updateDrinkRecipe(drinkRecipe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DrinkRecipe drinkRecipe0 = new DrinkRecipe();
      Long long0 = new Long((-10L));
      drinkRecipe0.setId(long0);
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.updateDrinkRecipe(drinkRecipe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DrinkRecipe drinkRecipe0 = new DrinkRecipe();
      Long long0 = new Long((-10L));
      drinkRecipe0.setId(long0);
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      ResponseEntity<DrinkRecipe> responseEntity0 = drinkRecipeWebService0.createDrinkRecipe(drinkRecipe0);
      assertFalse(responseEntity0.hasBody());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      DrinkRecipe drinkRecipe0 = new DrinkRecipe();
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.createDrinkRecipe(drinkRecipe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.getAllDrinkRecipes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      Long long0 = new Long((-10L));
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.getDrinkRecipe(long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DrinkRecipeWebService drinkRecipeWebService0 = new DrinkRecipeWebService();
      // Undeclared exception!
      try { 
        drinkRecipeWebService0.deleteDrinkRecipe((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.DrinkRecipeWebService", e);
      }
  }
}
