/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:02:00 GMT 2016
 */

package com.rickhanberryfinal.evosuite.webservices;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.Ingredients;
import com.rickhanberryfinal.webservices.IngredientsWebService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IngredientsWebService_ESTest extends IngredientsWebService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IngredientsWebService ingredientsWebService0 = new IngredientsWebService();
      // Undeclared exception!
      try { 
        ingredientsWebService0.updateIngredients((Ingredients) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.IngredientsWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IngredientsWebService ingredientsWebService0 = new IngredientsWebService();
      // Undeclared exception!
      try { 
        ingredientsWebService0.createIngredients((Ingredients) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.IngredientsWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IngredientsWebService ingredientsWebService0 = new IngredientsWebService();
      // Undeclared exception!
      try { 
        ingredientsWebService0.getAllIngredientss();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.IngredientsWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IngredientsWebService ingredientsWebService0 = new IngredientsWebService();
      Long long0 = new Long(0L);
      // Undeclared exception!
      try { 
        ingredientsWebService0.deleteIngredients(long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.IngredientsWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IngredientsWebService ingredientsWebService0 = new IngredientsWebService();
      Long long0 = new Long(17L);
      // Undeclared exception!
      try { 
        ingredientsWebService0.getIngredients(long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.IngredientsWebService", e);
      }
  }
}
