/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 29 15:02:00 GMT 2016
 */

package com.rickhanberryfinal.evosuite.webservices;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rickhanberryfinal.entities.Vendor;
import com.rickhanberryfinal.webservices.VendorWebService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VendorWebService_ESTest extends VendorWebService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VendorWebService vendorWebService0 = new VendorWebService();
      // Undeclared exception!
      try { 
        vendorWebService0.updateVendor((Vendor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.VendorWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VendorWebService vendorWebService0 = new VendorWebService();
      // Undeclared exception!
      try { 
        vendorWebService0.createVendor((Vendor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.VendorWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VendorWebService vendorWebService0 = new VendorWebService();
      // Undeclared exception!
      try { 
        vendorWebService0.deleteVendor((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.VendorWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VendorWebService vendorWebService0 = new VendorWebService();
      // Undeclared exception!
      try { 
        vendorWebService0.getVendor((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.VendorWebService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VendorWebService vendorWebService0 = new VendorWebService();
      // Undeclared exception!
      try { 
        vendorWebService0.getAllVendors();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.rickhanberryfinal.webservices.VendorWebService", e);
      }
  }
}
